-- Chạy đoạn mã SQL này trong trang SQL Editor của Supabase Dashboard của bạn:

CREATE TABLE catalogues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  size TEXT NOT NULL,
  type TEXT NOT NULL,
  link TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Kích hoạt RLS (Row Level Security)
ALTER TABLE catalogues ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách (policy) cho phép tất cả mọi người có thể xem danh sách catalogues
CREATE POLICY "Cho phép tất cả mọi người đọc catalogues" 
  ON catalogues FOR SELECT 
  USING (true);

-- Cho phép authenticated users (hoặc mọi người tuỳ vào cấu hình bảo mật) thêm/sửa/xóa
-- Nếu bạn muốn test nhanh không cần xác thực tài khoản Supabase:
CREATE POLICY "Cho phép thêm catalogues" ON catalogues FOR INSERT WITH CHECK (true);
CREATE POLICY "Cho phép sửa catalogues" ON catalogues FOR UPDATE USING (true);
CREATE POLICY "Cho phép xóa catalogues" ON catalogues FOR DELETE USING (true);
